[package]
name = "trustvector"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
