[workspace]
resolver = "2"

members = [
    "indexer",
    "attestation-transformer",
    "linear-combiner",
    "core-computer",
    "snap-score-computer",
    "job-manager",
    "proto-buf",
]

[workspace.package]
version = "0.0.1"
authors = [
    "Eugene Kim <ek@karma3labs.com>",
    "Jenya Nepoimannykh <jenya@karma3labs.com>",
    "Filip Lazovic <filip@karma3labs.com>",
]
edition = "2021"
