[package]
name = "indexer"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
serde = "1.0.192"
tokio = "1.33.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
web3 = "0.19.0"
